//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PeToolM.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PE_MAIN_WND                 102
#define IDI_MAIN_WND                    128
#define IDD_DLG_PE_FILE                 129
#define IDD_DLG_DOS_HDR                 130
#define IDD_DLG_FIL_HDR                 131
#define IDD_DLG_OPT_HDR                 132
#define IDD_DLG_DAT_DIR                 133
#define IDD_DLG_BLK_TBL                 134
#define IDD_DLG_IMP_TBL                 135
#define IDD_DLG_EXP_TBL                 136
#define IDD_DLG_RLC_TBL                 137
#define IDD_DLG_RES_TBL                 138
#define IDD_DLG_USR_OPR                 139
#define IDC_TAB_PETOOL                  1000
#define IDC_EDT_PE_FILE                 1003
#define IDC_BTN_OPEN_FILE               1004
#define IDC_STATIC_FILE_SIZE            1005
#define IDC_STATIC_CTIME                1006
#define IDC_STATIC_MTIME                1007
#define IDC_STATIC_ATIME                1008
#define IDC_STATIC_ATTRS                1009
#define IDC_EDT_DOS_MAGIC               1010
#define IDC_EDT_DOS_CBLP                1011
#define IDC_EDT_DOS_CP                  1012
#define IDC_EDT_DOS_CRLC                1013
#define IDC_EDT_DOS_CPARHDR             1014
#define IDC_EDT_FIL_NUMBEROFSECTION     1014
#define IDC_EDT_OPT_SIZEOFCODE          1014
#define IDC_EDT_EXP_TBL_MAJORVERSION    1014
#define IDC_EDT_RLC_TBL_SIZEOFBLOCK     1014
#define IDC_EDT_DOS_MINALLOC            1015
#define IDC_EDT_FIL_TIMEDATESTAMP       1015
#define IDC_EDT_OPT_SIZEOFINITIALIZEDDATA 1015
#define IDC_EDT_EXP_TBL_MINORVERSION    1015
#define IDC_EDT_RLC_TBL_BYTESOFRELOC    1015
#define IDC_EDT_DOS_MAXALLOC            1016
#define IDC_EDT_FIL_POINTERTOSYMBOLTABLE 1016
#define IDC_EDT_OPT_SIZEOFUNINITIALIZEDDATA 1016
#define IDC_EDT_EXP_TBL_NAME            1016
#define IDC_EDT_RLC_TBL_NUMBEROFRELOC   1016
#define IDC_EDT_DOS_SS                  1017
#define IDC_EDT_FIL_NUMBEROFSYMBOLS     1017
#define IDC_EDT_OPT_ADDRESSOFENTRYPOINT 1017
#define IDC_EDT_EXP_TBL_BASE            1017
#define IDC_EDT_DOS_SP                  1018
#define IDC_EDT_FIL_SIZEOFOPTIONALHEADER 1018
#define IDC_EDT_OPT_BASEOFCODE          1018
#define IDC_EDT_EXP_TBL_NUMBEROFFUNCTIONS 1018
#define IDC_EDT_DOS_CSUM                1019
#define IDC_EDT_FIL_CHARACTERISTICS     1019
#define IDC_EDT_OPT_BASEOFDATA          1019
#define IDC_EDT_EXP_TBL_NUMBEROFNAMES   1019
#define IDC_EDT_DOS_IP                  1020
#define IDC_EDT_OPT_IMAGEBASE           1020
#define IDC_EDT_EXP_TBL_ADDRESSOFFUNCTIONS 1020
#define IDC_EDT_DOS_CS                  1021
#define IDC_EDT_OPT_SECTIONALIGNMENT    1021
#define IDC_EDT_EXP_TBL_ADDRESSOFNAMES  1021
#define IDC_EDT_DOS_LFARLC              1022
#define IDC_EDT_OPT_FILEALIGNMENT       1022
#define IDC_EDT_EXP_TBL_ADDRESSOFNAMEORDINALS 1022
#define IDC_EDT_DOS_OVNO                1023
#define IDC_EDT_OPT_MAJOROPERATINGSYSTEMVERSION 1023
#define IDC_EDT_EXP_TBL_DLLNAME         1023
#define IDC_EDT_DOS_RES                 1024
#define IDC_EDT_OPT_MINOROPERATINGSYSTEMVERSION 1024
#define IDC_EDT_EXP_TBL_MKTIME          1024
#define IDC_EDT_DOS_OEMID               1025
#define IDC_EDT_OPT_MAJORIMAGEVERSION   1025
#define IDC_EDT_DOS_OEMINFO             1026
#define IDC_EDT_OPT_MINORIMAGEVERSION   1026
#define IDC_EDT_DOS_RES2                1027
#define IDC_EDT_OPT_MAJORSUBSYSTEMVERSION 1027
#define IDC_EDT_DOS_LFANEW              1028
#define IDC_EDT_FIL_SIGNATURE           1030
#define IDC_EDT_FIL_MACHINE             1031
#define IDC_EDT_OPT_MAGIC               1032
#define IDC_EDT_OPT_MAJORLINKERVERSION  1033
#define IDC_EDT_EXP_TBL_CHARACTERISTICS 1033
#define IDC_EDT_RLC_TBL_VIRTUALADDRESS  1033
#define IDC_EDT_OPT_MINORLINKERVERSION  1034
#define IDC_EDT_EXP_TBL_TIMEDATESTAMP   1034
#define IDC_EDT_RLC_TBL_FOA             1034
#define IDC_EDT_OPT_MINORSUBSYSTEMVERSION 1035
#define IDC_EDT_OPT_WIN32VERSIONVALUE   1036
#define IDC_EDT_OPT_SIZEOFIMAGE         1037
#define IDC_EDT_OPT_SIZEOFHEADERS       1038
#define IDC_EDT_OPT_CHECKSUM            1039
#define IDC_EDT_OPT_SUBSYSTEM           1040
#define IDC_EDT_OPT_DLLCHARACTERISTICS  1041
#define IDC_EDT_OPT_SIZEOFSTACKRESERVE  1042
#define IDC_EDT_OPT_SIZEOFSTACKCOMMIT   1043
#define IDC_EDT_OPT_SIZEOFHEAPRESERVE   1044
#define IDC_EDT_OPT_SIZEOFHEAPCOMMIT    1045
#define IDC_EDT_OPT_LOADERFLAGS         1046
#define IDC_EDT_OPT_NUMBEROFRVAANDSIZES 1047
#define IDC_EDT_OPT_DATA_DIR            1048
#define IDC_LIST_DATA_DIRECTORY         1049
#define IDC_LIST_SECTION_TABLE          1050
#define IDC_LIST_IMPORT_TABLE           1051
#define IDC_LIST_IMPORT_DETAIL          1052
#define IDC_LIST_EXPORT_TABLE           1053
#define IDC_LIST_BASE_RELOCATION        1054
#define IDC_STATIC_GRP_ADDR_CONVERT     1055
#define IDC_EDT_ADDR_SRC                1056
#define IDC_EDT_ADDR_DST                1057
#define IDC_BTN_ADDRESS_CONVERT         1058
#define IDC_STATIC_SRC                  1059
#define IDC_STATIC_DST                  1060
#define IDC_CHECK_ADDRESS_CONVERT       1061
#define IDC_STATIC_GRP_SRCH_IMPORT      1062
#define IDC_EDT_SRCH_IMP_KEY            1063
#define IDC_BTN_SEARCH_IMPORT           1064
#define IDC_EDT_SRCH_IMP_RESULT         1065
#define IDC_STATIC_GRP_SRCH_EXPORT      1066
#define IDC_EDT_SRCH_EXP_KEY            1067
#define IDC_BTN_SEARCH_EXPORT           1068
#define IDC_EDT_SRCH_EXP_RESULT         1069
#define IDC_TREE_RESOURCE_TABLE         1070
#define IDC_EDT_RES_TBL_DATA            1071
#define IDC_STATIC_GRP_SIGN             1072
#define IDC_EDT_SIGN_SOFT_NAME          1073
#define IDC_EDT_SIGN_VER1               1074
#define IDC_EDT_SIGN_VER2               1075
#define IDC_EDT_SIGN_VER3               1077
#define IDC_EDT_SIGN_AUTHOR             1078
#define IDC_EDT_SIGN_EMAIL              1079
#define IDC_BTN_SOFT_SIGN               1080
#define IDC_STATIC_SOFT_NAME            1081
#define IDC_STATIC_SOFT_VERSION         1082
#define IDC_STATIC_SOFT_AUTHOR          1083
#define IDC_STATIC_EMAIL                1084
#define IDC_STC_TOOL_VERSION            1085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
